### ISSUE TITLE
a bug of options.enable_MLDOM?

### ISSUE THREAD

**Issue by bwtang** [cwfletcher/sdo#1]
I run your code in O3 CPU with the parameters like the example in sample_script dir. However, it failed and reported such info:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tbw/workspace/sdo-master/src/python/m5/main.py", line 436, in main
    exec filecode in scope
  File "/home/tbw/workspace/sdo-master/configs/example/spec06_config.py", line 377, in <module>
    Ruby.create_system(options, False, system)
  File "/home/tbw/workspace/sdo-master/configs/ruby/Ruby.py", line 188, in create_system
    ruby.enable_MLDOM = options.enable_MLDOM
AttributeError: Values instance has no attribute 'enable_MLDOM'

I review the file configs/common/Options.py and  can't find the attribute `enable_MLDOM`. So I think it's a bug of your code. Is that right? How can I fix it?

**Comment by bwtang** [comment]
I just set the `ruby.enable_MLDOM = True` and this time the code can run correctly. Then I use SPEC CPU 2006 benchmarks to evaluate its performance. However most of benchmarks hang over three days. Something must be wrong. The parametters I used are shown below.

--at-instruction -r 10000000000 -I 1000000000 \
--num-cpus=1 --mem-size=4GB \
--cpu-type=DerivO3CPU --ruby --num-dirs=1 --network=simple --topology=Mesh_XY --mesh-rows=1 \
--scheme=SDO --mem_model=TSO --threat_model=Futuristic --impChannel=1 --STT --enable_SDO \
--pred_type=tournament_2way --subpred1_type=greedy --subpred2_type=loop --pred_option=0 --TLB_defense=SDO

I have generated the checkpoint of each benchmark with Atomic CPU Model.  The hanging benchmarks are "
gromacs, calculix, bzip2, perlbench, povray, bwaves, h264ref, libquantum, mcf, wrf, hmmer, cactusADM, lbm, omnetpp, GemsFDTD, milc, namd, gamess".

**Comment by jiyongyu** [comment]
Thank you for pointing out the _enable_MLDOM_ issue. I have changed the options. Please take a look.

I don't know why these benchmarks seem to fail. I have tested these SPEC06 benchmarks and they all ran successfully.

Can you provide more information? (notice that you have to use X86_MESI_Three_Level. Other configurations are not supported)

It'll be easier to troubleshoot if you can find the place where these benchmarks get stuck.

**Comment by bwtang** [comment]
Thank you for your reply. It seems like the parameters are right, because some benchmarks finished successfully, such as 'gcc'. This is part of cmdline output file of an abnormal benchmark (bwaves).

===================================================
warn: Memory mode will be changed to atomic_noncaching
 gem5 Simulator System.  http://gem5.org
 gem5 is copyrighted software; use the --copyright option for details.
 
 gem5 compiled Dec 29 2020 13:01:37
 gem5 started Dec 31 2020 11:19:38
 gem5 executing on hby3-X785-G30, pid 29054
 command line: /home/tbw/workspace/sdo-master/build/X86_MESI_Three_Level/gem5.fast --outdir=/home/tbw/workspace/sdo-master/  
 output/SPEC-bwaves /home/tbw/workspace/sdo-master/configs/example/spec06_config.py --benchmark=bwaves --benchmark_stdout=/  
 home/tbw/workspace/sdo-master/output/SPEC-bwaves/bwaves.out --benchmark_stderr=/home/tbw/workspace/sdo-master/output/SPEC-  
 bwaves/bwaves.err --num-cpus=1 --mem-size=4GB --at-instruction -r 10000000000 -I 1000000000 --scheme=SDO --mem_model=TSO --- threat_model=Futuristic --impChannel=1 --STT --enable_SDO --pred_type=tournament_2way --subpred1_type=greedy --subpred2_type=loop --pred_option=0 --TLB_defense=SDO --cpu-type=DerivO3CPU --ruby --num-dirs=1 --network=simple --topology=Mesh_XY --mesh-rows=1
 
 info: Standard input is not a terminal, disabling listeners.
 Selected SPEC_CPU2006 benchmark
 --> bwaves
 Process stdout file: /home/tbw/workspace/sdo-master/output/SPEC-bwaves/bwaves.out
 Process stderr file: /home/tbw/workspace/sdo-master/output/SPEC-bwaves/bwaves.err
 ['bwaves_base.test']

 info: Configure for DerivO3CPU. scheme=SDO; mem_model=TSO, MSHR_size=16
 STT=1; impChannel=1

SDO enabled = 1
SDO predictor is: tournament_2way

 Global frequency set at 1000000000000 ticks per second
 warn: DRAM device capacity (8192 Mbytes) does not match the address range assigned (4096 Mbytes)
 RubySystem: MLDOM enabled!
 RubySystem: OblS_contention_disabled
 Sequencer of core 99 has max_outstanding_requests=16
 Info: simulation uses scheme: SDO; needsTSO=1
  threat model is Futuristic
 isInvisiSpec = 1, applySTT = 1, implicit channel = 1, ifPrintROB = 0, moreTransTypes = 0
 consider loads as transmitters (explicit channel)
 SDO is enabled!
 SDO chooses tournament_2Way (greedy + loop). delay_on_LLC = 0, delay_on_DRAM = 0
 CPU creates a tournament_2way predictor
 Exposeonly = 0
 Disable 2ndld = 0
 warn: Sockets disabled, not accepting gdb connections
 warn: Checkpoints for file descriptors currently do not work.
 Switch at curTick count:10000
 info: Entering event queue @ 9848868012000.  Starting simulation...
 Switched CPUS @ tick 9848868022000
 switching cpus 
 warn: ClockedObject: Already in the requested power state, request ignored
  REAL SIMULATION 
 info: Entering event queue @ 9848868022000.  Starting simulation...
 warn: Replacement policy updates recently became the responsibility of SLICC state machines. Make sure to setMRU() near     
 callbacks in .sm files!
 warn: Replacement policy updates recently became the responsibility of SLICC state machines. Make sure to setMRU() near     
 callbacks in .sm files!
----------------------------
 numCommittedInst = 1000000
 nonspec avg L0 latency: 2
 nonspec avg L1 latency: 16
 No nonspec L2 access!
 nonspec avg Mem latency: 340
 spec avg L0 latency: 2
 No spec L1 access!
 No spec L2 access!
 spec avg Mem latency: 295
===================================================

The end of file is stopped at "@@numCommittedInst = 74000000".   Do you have some advice about the problem?

**Comment by jiyongyu** [comment]
You should just monitor this "numCommittedInst" output from condor.output to see if the program is making progress. It might just need a bit more time to finish. I have tested SPEC06 benchmarks using simpoints and they all generate results. If the benchmarks really get stuck in the middle, you can pinpoint where it gets stuck for a certain benchmark experiment and see what goes wrong.

**Comment by bwtang** [comment]
I'm very sorry, I have find the problem. The benchmark is stuck because the disk is full, they cannot write the output file.
